### ISSUE TITLE
Use of Undefined Constant DS - Assumed 'DS'

### ISSUE THREAD

**Issue by same-ghost** [schnti/kirby3-cachebuster#1]
Fresh install on Kirby 3.1.2 threw the above error. I just copied and pasted `define('DS', '/'); `from `/kirby/bootstrap.php` and it seemed to fix the issue.

I don't know a lot about PHP, so I don't know if that will have unintended consequences, or if there's a better way of doing it.

**Comment by schnti** [comment]
I fixed the error with this line of code:

`defined('DS') or define('DS', '/');`
